driver:
  name: docker

platforms:
  - name: centos-7
    driver_config:
      image: corux/centos7-salt
      cap_add:
        - SYS_ADMIN
      run_command: /usr/sbin/init

provisioner:
  name: salt_solo
  formula: atlassian-bamboo
  vendor_path: srv/salt
  pillars-from-files:
    atlassian-bamboo.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - atlassian-bamboo
  state_top:
    base:
      "*":
        - atlassian-bamboo.server

suites:
  - name: default
